name: Daily Reservations Generator

on:
  schedule:
    - cron: '0 1 * * *'  # runs every day at 1:00 AM UTC
  workflow_dispatch:      # allows manual runs

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run your script
        run: |
          mkdir -p output state
          python generate_daily_reservations.py

      - name: Upload CSV as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Daily-Reservations
          path: output/*.csv
          retention-days: 14  # keep for 2 weeks

      - name: Email daily CSV
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Daily Reservations CSV - $(date +'%Y-%m-%d')"
          body: |
            Hello 👋  

            Here is your automatically generated Reservations CSV for today.  
            The file includes 100 reservations generated from your business rules.  

            You can also download it directly from the workflow run page under “Artifacts.”

            Have a great day!  
            — Your Automated Booking Engine 🤖
          to: yourname@gmail.com
          from: ${{ secrets.MAIL_USERNAME }}
          attachments: output/Reservations_*.csv
