name: Daily Reservations Generator

on:
  schedule:
    - cron: '0 1 * * *'  # runs every day at 1:00 AM UTC
  workflow_dispatch:      # lets you run it manually too

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Get your code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run your script
        run: |
          mkdir -p output state
          python generate_daily_reservations.py

      - name: Save new file
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add output/ state/
          git commit -m "Daily reservations CSV for $(date +'%Y-%m-%d')" || echo "No changes"
          git push
