name: Daily Reservations Generator

on:
  schedule:
    - cron: '0 1 * * *'  # runs every day at 1:00 AM UTC
  workflow_dispatch:      # lets you run it manually too

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
     - name: Get your code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run your script
        run: |
          mkdir -p output state
          python generate_daily_reservations.py

      - name: Save new file
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch origin main
          git checkout main
          git reset --soft origin/main
          git add output/ state/
          git commit -m "Daily reservations CSV for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push origin main



      - name: Email daily CSV
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Your Daily Reservations CSV"
          body: |
            Hello 👋  

            Here is your automatically generated Reservations CSV for today.  
            The file includes 100 reservations, generated based on your business rules.  

            Have a great day!  
            — Your Automated Booking Engine 🤖
          to: yourname@gmail.com
          from: ${{ secrets.MAIL_USERNAME }}
          attachments: output/Reservations_*.csv
