name: Daily Reservations Generator

on:
  schedule:
    - cron: '0 1 * * *'  # runs every day at 1:00 AM UTC
  workflow_dispatch:      # allows manual runs
  push:
    paths-ignore:
      - '.github/workflows/**'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Get your code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run your script
        run: |
          mkdir -p output state
          python generate_daily_reservations.py

      - name: Upload daily CSV as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Daily-Reservations-CSV
          path: output/*.csv
          retention-days: 7   # keep artifact for 7 days

      - name: Email daily CSV
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Your Daily Reservations CSV"
          body: |
            Hello 👋  

            Here is your automatically generated Reservations CSV for today.  
            The file includes 100 reservations generated from your business rules.  

            You can also download it directly from the workflow run page under “Artifacts.”

            Have a great day!  
            — Your Automated Booking Engine 🤖
          to: yourname@gmail.com
          from: ${{ secrets.MAIL_USERNAME }}
          attachments: output/Reservations_*.csv
